spring.application.name=UpsolveIO

# Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://dpg-d6ll7nvtskes73c2cmt0-a.oregon-postgres.render.com/upsolve_io_database
spring.datasource.username=upsolve_io_database_user
spring.datasource.password=wQJDKUlVz8F3frBOG7qCiN6ddkG7vomj

